### PR TITLE
Added docker-compose file for front-end

### PR DESCRIPTION
**Pull request by andreicozma1**
This docker-compose.yml file uses the Dockerfile in the Front-End folder in order to spawn up the front-end.
Please see the related FE-17 pull request for the Front-End repo which is required for this to work.

```
      ports:
         - "3000:3000"
```
This line exposes the port 3000 inside docker to port 3000 on the host machine.

### CODE REVIEW

**Review by ObsidianSkin — DISMISSED** [review]

**Comment by ObsidianSkin** [comment]
tried to build after fetching smart ledger and changing to fe-17 branch. got this error:
```
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/bu
ildkit-mount767248585/Dockerfile: no such file or directory
ERROR: Service 'client' failed to build : Build failed
```
i tried running `docker build .` but this was when i was just working in the front end repo.
also, i noticed the folders for front-end and back-end were empty (and up to date) after pulling the smart ledger repo, is that intended?

**Comment by ObsidianSkin** [comment]
ok so obv the two submodules being empty is not intended. to fix this i cloned the repo again except i used the `--recurse-submodules` flag like this
`git clone --recurse-submodules https://github.com/CS401-Team-Project/Smart-Ledger.git`
however, after trying docker again i got this error:
`failed to compute cache key: "/package-lock.json" not found: not found`

**Comment by andreicozma1** [comment]
> ok so obv the two submodules being empty is not intended. to fix this i cloned the repo again except i used the `--recurse-submodules` flag like this `git clone --recurse-submodules https://github.com/CS401-Team-Project/Smart-Ledger.git` however, after trying docker again i got this error: `failed to compute cache key: "/package-lock.json" not found: not found`

I found a better way to automatically clone and recurse all submodules. It's a global configuration you run like this:
```
git config --global submodule.recurse true
```
Could you try the command above, then re-clone a clean SL repo from scratch? It should automatically clone both submodules and checkout a corresponding commit for each (it won't be on a branch but a specific commit).

Note: Make sure you are on the newest commit of Front-End - the Dockerfile should say `FROM node:16.14.0` at the top instead of `FROM node:latest`

To start up the server you will need Docker-Compose to be able to run the command `docker-compose up -d` from the same directory as the `docker-compose.yml` file.
Let me know if that fixes the issues on your side!

**Comment by ObsidianSkin** [comment]
hm, so i got the submodules to pull after initializing them with the following commands (and updating git just in case)
```
git submodule init
git submodule update
```
however, when i try to run `docker-compose` in the "Smart Ledge" dir i still get the following error
```
failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/package-lock.json" not found: not found
```
could this have something to do with my windows environment? has anyone been able to get docker running on windows or encountered similar issues on unix machines

**Review by ObsidianSkin — APPROVED** [review]
thanks for helping me get it working :)

**Pull request merged**
